import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ENV } from "@/configs/environment";
import AppLayout from "@/interfaces/layouts/app.layout";
import { ProviderReduxToolkit } from "@/providers/redux.provider";
import { ProviderTanstack } from "@/providers/tanstack.provider";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<NextTopLoader
					height={2}
					color={ENV.LOADER_COLOR}
					showSpinner={false}
				/>
				<ProviderReduxToolkit>
					<ProviderTanstack>
						<AppLayout>{children}</AppLayout>
					</ProviderTanstack>
				</ProviderReduxToolkit>
			</body>
		</html>
	);
}
