# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: vue-frontend
package: your-package

# Directory
dir:
  # client
  hook: src/hooks
  component: src/components
  layout: src/layouts
